# Generated by Django 5.1.7 on 2025-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0002_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancestyle',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='instructors/')),
                ('bio', models.TextField()),
                ('expertise', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField()),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('dance_styles', models.ManyToManyField(related_name='instructors', to='dance_styles.dancestyle')),
            ],
        ),
    ]
