# Generated by Django 5.1.7 on 2025-05-05 16:50

from django.db import migrations


def add_sample_instructors(apps, schema_editor):
    DanceStyle = apps.get_model('dance_styles', 'DanceStyle')
    Instructor = apps.get_model('dance_styles', 'Instructor')
    
    # Sample instructors data
    instructors_data = [
        {
            'name': 'Isabella Martinez',
            'bio': 'International Latin dance champion with over 15 years of experience. Trained in Cuba and Spain, Isabella brings authentic Latin flair to her classes.',
            'expertise': 'Latin Dance Specialist',
            'years_of_experience': 15,
            'facebook_link': 'https://facebook.com/isabelladance',
            'instagram_link': 'https://instagram.com/bella.dances',
            'styles': ['Salsa', 'Bachata', 'Cha Cha']
        },
        {
            'name': 'James Chen',
            'bio': 'Former principal dancer at the Royal Ballet Academy. James combines classical technique with modern innovation in his teaching approach.',
            'expertise': 'Contemporary & Ballet',
            'years_of_experience': 12,
            'instagram_link': 'https://instagram.com/james.dances',
            'linkedin_link': 'https://linkedin.com/in/jameschendance',
            'styles': ['Ballet', 'Contemporary', 'Modern']
        },
        {
            'name': 'Aisha Patel',
            'bio': 'Bollywood choreographer who has worked with top Indian film studios. Brings high energy and authentic Indian dance techniques to her classes.',
            'expertise': 'Bollywood & Indian Classical',
            'years_of_experience': 10,
            'instagram_link': 'https://instagram.com/aisha.bollywood',
            'twitter_link': 'https://twitter.com/aishaDance',
            'styles': ['Bollywood', 'Kathak', 'Folk Dance']
        },
        {
            'name': 'Marcus Johnson',
            'bio': 'Hip-hop pioneer who has performed with major artists. Specializes in various urban dance styles and breaking.',
            'expertise': 'Hip-Hop & Street Dance',
            'years_of_experience': 18,
            'instagram_link': 'https://instagram.com/marcus.breaks',
            'twitter_link': 'https://twitter.com/marcusHipHop',
            'styles': ['Hip Hop', 'Breaking', 'Street Jazz']
        },
        {
            'name': 'Sofia Petrova',
            'bio': 'Former Russian ballet soloist turned ballroom specialist. Known for her elegant teaching style and attention to detail.',
            'expertise': 'Ballroom & Ballet',
            'years_of_experience': 20,
            'facebook_link': 'https://facebook.com/sofia.dances',
            'instagram_link': 'https://instagram.com/sofia.ballroom',
            'styles': ['Waltz', 'Tango', 'Ballet']
        }
    ]
    
    # Create instructors
    for instructor_data in instructors_data:
        instructor = Instructor.objects.create(
            name=instructor_data['name'],
            bio=instructor_data['bio'],
            expertise=instructor_data['expertise'],
            years_of_experience=instructor_data['years_of_experience'],
            facebook_link=instructor_data.get('facebook_link', ''),
            instagram_link=instructor_data.get('instagram_link', ''),
            twitter_link=instructor_data.get('twitter_link', ''),
            linkedin_link=instructor_data.get('linkedin_link', '')
        )
        
        # Get or create dance styles and add them to instructor
        for style_name in instructor_data['styles']:
            style, _ = DanceStyle.objects.get_or_create(
                name=style_name,
                defaults={
                    'description': f'Learn {style_name} from our expert instructors',
                    'choreographer': instructor.name,
                    'registration_fee': 99.99
                }
            )
            instructor.dance_styles.add(style)

def remove_sample_instructors(apps, schema_editor):
    Instructor = apps.get_model('dance_styles', 'Instructor')
    Instructor.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0003_alter_dancestyle_registration_fee_instructor'),
    ]

    operations = [
        migrations.RunPython(add_sample_instructors, remove_sample_instructors),
    ]
