# Generated by Django 5.1.7 on 2025-05-05 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0006_event_eventregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='available_slots',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dance_styles.instructor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='dance_styles',
            field=models.ManyToManyField(to='dance_styles.dancestyle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance_styles.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='payment_date',
        ),
    ]
