# Generated by Django 5.1.7 on 2025-05-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0007_rename_end_time_event_time_and_more'),
    ]

    operations = [
    ]
