# Generated by Django 5.1.7 on 2025-05-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance_styles', '0008_add_sample_events'),
    ]

    operations = [
    ]
